# Generated by Django 5.1.4 on 2024-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cp_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=50)),
                ('cp_email', models.EmailField(default='', max_length=254)),
                ('cp_password', models.CharField(max_length=50)),
                ('cp_phone', models.IntegerField(default='')),
                ('cp_gst_no', models.CharField(max_length=50)),
                ('cp_address', models.TextField(default='')),
            ],
        ),
    ]
