# Generated by Django 5.1.4 on 2024-12-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cp_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cp_register',
            name='cp_email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='cp_register',
            name='cp_phone',
            field=models.IntegerField(default=' '),
        ),
    ]
