# Generated by Django 5.1.4 on 2024-12-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_cp_register_cp_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cp_register',
            name='cp_phone',
            field=models.CharField(max_length=50),
        ),
    ]
