# Generated by Django 5.0.6 on 2025-01-01 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_cp_register_cp_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
